spring.application.name=User-Service
server.port=8082

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/User_Service
spring.datasource.username=root
spring.datasource.password=Tejas@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#It is used to save the logs
#logging.file.name=logs/user_service.log