server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true